import type { Metadata } from "next";
import "./globals.css";
import { Orbitron, Albert_Sans } from "next/font/google";
import FrameNavbar from "@/components/atoms/svg/FrameNavbar";
import SVGNavSide from "@/components/atoms/svg/SVGNavSide";
import Link from "next/link";
import TextHeading3 from "@/components/atoms/typography/TextHeading3";
import TextHeading4 from "@/components/atoms/typography/TextHeading4";
import TextBody from "@/components/atoms/typography/TextBody";
import Image from "next/image";
import NavLink from "@/components/molecules/Links/NavLink";
import Navbar from "@/components/organisms/Navbar";

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const albert_sans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${orbitron.variable} ${albert_sans.variable}`}
    >
      <body className="bg-blue-dark min-h-screen min-w-screen flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
